#!/usr/bin/env bash
# Writes extension/config.generated.js from /etc/runready-kiosk/config.env

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${RUNREADY_KIOSK_CONFIG:-/etc/runready-kiosk/config.env}"
OUTPUT="${SCRIPT_DIR}/extension/config.generated.js"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "Missing config: $CONFIG_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$CONFIG_FILE"

if [[ -z "${RUNREADY_AUTH_TOKEN:-}" ]]; then
  echo "RUNREADY_AUTH_TOKEN is not set in $CONFIG_FILE" >&2
  exit 1
fi

token_json=$(python3 - <<'PY' "$RUNREADY_AUTH_TOKEN"
import json, sys
print(json.dumps(sys.argv[1]))
PY
)

org_json=$(python3 - <<'PY' "${RUNREADY_ORGANIZATION_ID:-}"
import json, sys
print(json.dumps(sys.argv[1] if len(sys.argv) > 1 else ""))
PY
)

calendar_kiosk="false"
if [[ "${RUNREADY_CALENDAR_KIOSK_MODE:-}" == "true" ]]; then
  calendar_kiosk="true"
fi

force_sync="false"
if [[ "${RUNREADY_FORCE_TOKEN_SYNC:-}" == "true" ]]; then
  force_sync="true"
fi

cat >"$OUTPUT" <<EOF
// Generated by generate-extension-config.sh — do not edit by hand.
var RUNREADY_KIOSK = {
  token: ${token_json},
  organizationId: ${org_json},
  calendarKioskMode: ${calendar_kiosk},
  forceTokenSync: ${force_sync}
};
EOF

chmod 644 "$OUTPUT"
# Chromium runs as the desktop user — it must be able to read the extension scripts.
if [[ -n "${RUNREADY_DESKTOP_USER:-}" ]] && id "${RUNREADY_DESKTOP_USER}" &>/dev/null; then
  chown root:"$(id -gn "${RUNREADY_DESKTOP_USER}")" "$OUTPUT" 2>/dev/null || chmod a+r "$OUTPUT"
else
  chmod a+r "$OUTPUT"
fi
